name: Build Apptainer Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to manually trigger the build from the GitHub UI

jobs:
  build: # This first step uses apptainer to build the .sif image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.1

      - name: Build Apptainer Image # Here sudo can be used because of github settings
        run: |
          sudo apptainer build astralog.sif Singularity.def

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: astralog-sif-image
          path: astralog.sif
          retention-days: 7

  deploy:
    name: Deploy to CINECA G100
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (for job.sh and input files)
        uses: actions/checkout@v4

      - name: Download Apptainer Image
        uses: actions/download-artifact@v4
        with:
          name: astralog-sif-image
          path: .

      - name: Setup SSH Keys and Certificate # For this step to work both secrets must be updated
        env:
          SSH_KEY: ${{ secrets.CINECA_SSH_KEY }}
          SSH_CERT: ${{ secrets.CINECA_SSH_CERT }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_cineca
          chmod 600 ~/.ssh/id_cineca
          echo "$SSH_CERT" > ~/.ssh/id_cineca-cert.pub
          chmod 644 ~/.ssh/id_cineca-cert.pub

      - name: Copy Files to CINECA (Native SCP) # The option StrictHostKeyChecking=no 
                                                # enables MITM attacks but is the only way to manage key changes
                                                # on Github runner
        run: |
          scp -v -o StrictHostKeyChecking=no -o CertificateFile=~/.ssh/id_cineca-cert.pub -i ~/.ssh/id_cineca -r astralog.sif job.sh input/ ${{ secrets.CINECA_USERNAME }}@login.g100.cineca.it:~/astralog_project/

      - name: Submit Job on SLURM (Native SSH)
        run: |
          ssh -v -o StrictHostKeyChecking=no -o CertificateFile=~/.ssh/id_cineca-cert.pub -i ~/.ssh/id_cineca ${{ secrets.CINECA_USERNAME }}@login.g100.cineca.it << 'EOF'
            cd ~/astralog_project
            module load apptainer || echo "Module already loaded"
            echo "Submitting SLURM job..."
            sbatch job.sh
          EOF
