name: Build Singularity Container

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.0

      - name: Build Singularity Container
        run: |
          singularity build --fakeroot astralog.sif Singularity.def

      - name: Upload Container as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: astralog-container
          path: astralog.sif
